 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.terraformersmc.modmenu.util.mod.neoforge;

import com.terraformersmc.modmenu.ModMenu;
import com.terraformersmc.modmenu.util.mod.Mod;
import com.terraformersmc.modmenu.util.mod.ModBadge;
import com.terraformersmc.modmenu.util.mod.Mod.ModMenuData.DummyParentData;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.SortedMap;
import java.util.TreeMap;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.util.Tuple;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.ModList;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public class NeoforgeDummyParentMod implements Mod {
   private final String id;
   private final Mod host;
   private boolean childHasUpdate;
   private final Set<String> badgeNames = new LinkedHashSet();
   private final Set<ModBadge> badges = new LinkedHashSet();

   public NeoforgeDummyParentMod(Mod host, String id) {
      this.host = host;
      this.id = id;
      DummyParentData parentData = host.getModMenuData().getDummyParentData();
      if (parentData != null) {
         this.badgeNames.addAll(parentData.getBadges());
      }

      if (id.equals("fabric-api")) {
         this.badgeNames.add("library");
      }

   }

   @NotNull
   public String getId() {
      return this.id;
   }

   @NotNull
   public String getName() {
      DummyParentData parentData = this.host.getModMenuData().getDummyParentData();
      if (parentData != null) {
         return (String)parentData.getName().orElse("");
      } else {
         return this.id.equals("fabric-api") ? "Fabric API" : this.id;
      }
   }

   @NotNull
   public Tuple<DynamicTexture, Dimension> getIcon(NeoforgeIconHandler iconHandler, int i, boolean isSmall) {
      String iconSourceId = this.host.getId();
      String iconResourceId = this.id + (isSmall ? "_small" : "");
      if (NeoforgeIconHandler.modResourceIconCache.containsKey(iconResourceId)) {
         return (Tuple)NeoforgeIconHandler.modResourceIconCache.get(iconResourceId);
      } else {
         DummyParentData parentData = this.host.getModMenuData().getDummyParentData();
         String iconPath = null;
         if (parentData != null) {
            iconPath = (String)parentData.getIcon().orElse(null);
         }

         if ("inherit".equals(iconPath)) {
            return this.host.getIcon(iconHandler, i, isSmall);
         } else {
            if (iconPath == null) {
               iconSourceId = "modmenu";
               if (this.id.equals("fabric-api")) {
                  iconPath = "assets/modmenu/fabric.png";
               } else {
                  iconPath = "assets/modmenu/unknown_parent.png";
               }
            }

             String finalIconSourceId = iconSourceId;
             ModContainer iconSource = (ModContainer)ModList.get().getModContainerById(iconSourceId).orElseThrow(() -> {
               return new RuntimeException("Cannot get ModContainer for Fabric mod with id " + finalIconSourceId);
            });
            Tuple<DynamicTexture, Dimension> created = iconHandler.createIcon(iconSource, iconPath);
            if (created == null) {
               ModMenu.LOGGER.warn("Icon for mod {} not found at {} - falling back to bundled unknown_parent.png", this.getId(), iconPath);
               Optional<? extends ModContainer> optFallback = ModList.get().getModContainerById("modmenu");
               ModContainer fallbackSource = iconSource;
               if (optFallback.isPresent()) {
                  fallbackSource = (ModContainer)optFallback.get();
               }

               String fallbackPath = "assets/modmenu/unknown_parent.png";
               created = iconHandler.createIcon(fallbackSource, fallbackPath);
               if (created != null) {
                  NeoforgeIconHandler.modResourceIconCache.put(iconResourceId, created);
                  return created;
               } else {
                  try {
                     if (!Objects.equals(this.host.getId(), this.getId())) {
                        Tuple<DynamicTexture, Dimension> hostIcon = this.host.getIcon(iconHandler, i, isSmall);
                        if (hostIcon != null) {
                           return hostIcon;
                        }
                     }
                  } catch (Throwable var14) {
                     ModMenu.LOGGER.warn("Final fallback: host icon lookup failed for {}: {}", this.getId(), var14.getMessage());
                  }

                  ModMenu.LOGGER.error("Failed to load icon for {} (tried {} and {}), returning null texture placeholder", new Object[]{this.getId(), iconPath, "assets/modmenu/unknown_parent.png"});
                  return null;
               }
            } else {
               return created;
            }
         }
      }
   }

   @NotNull
   public String getDescription() {
      DummyParentData parentData = this.host.getModMenuData().getDummyParentData();
      ModMenu.LOGGER.info(parentData.getDescription().get());
      return parentData != null ? (String)parentData.getDescription().orElse("") : "";
   }

   @NotNull
   public String getVersion() {
      return "";
   }

   @NotNull
   public String getPrefixedVersion() {
      return "";
   }

   @NotNull
   public List<String> getAuthors() {
      return new ArrayList();
   }

   @NotNull
   public Map<String, Collection<String>> getContributors() {
      return Map.of();
   }

   @NotNull
   public SortedMap<String, Set<String>> getCredits() {
      return new TreeMap();
   }

   @NotNull
   public Set<ModBadge> getBadges() {
      return this.badges;
   }

   @NotNull
   public Set<String> getBadgeNames() {
      return this.badgeNames;
   }

   @Nullable
   public String getWebsite() {
      return null;
   }

   @Nullable
   public String getIssueTracker() {
      return null;
   }

   @Nullable
   public String getSource() {
      return null;
   }

   @Nullable
   public String getParent() {
      return null;
   }

   @NotNull
   public Set<String> getLicense() {
      return new HashSet();
   }

   @NotNull
   public Map<String, String> getLinks() {
      return new HashMap();
   }

   public boolean isReal() {
      return false;
   }

   public boolean getChildHasUpdate() {
      return this.childHasUpdate;
   }

   public void setChildHasUpdate() {
      this.childHasUpdate = true;
   }

   public boolean isHidden() {
      return ((List)ModMenu.getConfig().HIDDEN_MODS.get()).contains(this.getId());
   }

   public ModMenuData getModMenuData() {
      return this.host.getModMenuData();
   }

   public Optional<ModContainer> getContainer() {
      return Optional.empty();
   }
}
